# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Mod properties
mod_version=4.19.19
maven_group=invoker54
archives_name=invocore
enabled_platforms=fabric,forge
mod_description=Another library mod, makes tasks simpler and less repetitive
# Minecraft properties
minecraft_version=1.20.1
# Dependencies
architectury_api_version=9.2.14
fabric_loader_version=0.17.2
fabric_api_version=0.92.6+1.20.1
forge_version=1.20.1-47.4.9
# Parchment version
parchment_version = 2023.09.03
# Access Widener (Access Transformer)
access_widener_path = src/main/resources/invocore.accesswidener